/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PHONE_BOOK_H_RPCGEN
#define _PHONE_BOOK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct record {
	char *name;
	char *address;
	char *phone;
};
typedef struct record record;

#define PHONE_BOOK 1111111
#define PHONE_BOOK_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define CREATE 1
extern  int * create_1(record *, CLIENT *);
extern  int * create_1_svc(record *, struct svc_req *);
#define READ 2
extern  record * read_1(char *, CLIENT *);
extern  record * read_1_svc(char *, struct svc_req *);
#define UPDATE 3
extern  int * update_1(record *, CLIENT *);
extern  int * update_1_svc(record *, struct svc_req *);
#define DELETE 4
extern  int * delete_1(char *, CLIENT *);
extern  int * delete_1_svc(char *, struct svc_req *);
extern int phone_book_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CREATE 1
extern  int * create_1();
extern  int * create_1_svc();
#define READ 2
extern  record * read_1();
extern  record * read_1_svc();
#define UPDATE 3
extern  int * update_1();
extern  int * update_1_svc();
#define DELETE 4
extern  int * delete_1();
extern  int * delete_1_svc();
extern int phone_book_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_record (XDR *, record*);

#else /* K&R C */
extern bool_t xdr_record ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PHONE_BOOK_H_RPCGEN */
