/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "phone_book.h"

bool_t
xdr_record (XDR *xdrs, record *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->address, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->phone, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
